In [4]:
#Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

import numpy as np
x = np.array([7, 2])
y = np.array([3, 1])
print("Original numbers:")
print(x)
print(y)
print("greater:")
print(np.greater(x, y))
print("greater_equal:")
print(np.greater_equal(x, y))
print("less than:")
print(np.less(x, y))
print("less_equal
[False False]
less_equal:
[:")
print(np.less_equal(x, y))

Original numbers:
[7 2]
[3 1]
greater:
[ True  True]
greater_equal:
[ True  True]
less than:
[False False]
less_equal:
[False False]


In [6]:
# Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives
import numpy as np
array=np.zeros(10)
print("array of 10 zeros:")
print(array)
array=np.ones(10)
print("array of 10 ones:")
print(array)
array=np.ones(10)*5
print("array of 10 fives:")
print(array)

array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [8]:
# Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
#given array

import numpy as np
x = np.array([[5,4],[2,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))


Original array:
[[5 4]
 [2 3]]
Sum of all elements:
14
Sum of each column:
[7 7]
Sum of each row:
[9 5]


In [10]:
#Write a NumPy program to add, subtract, multiply, divide arguments element-wise.
import numpy as np
print("Add:")
print(np.add(5.0, 4.0))
print("Subtract:")
print(np.subtract(9.0, 15.0))
print("Multiply:")
print(np.multiply(14.0, 28.0))
print("Divide:")
print(np.divide(33.0, 10.0))

Add:
9.0
Subtract:
-6.0
Multiply:
392.0
Divide:
3.3


In [13]:
#Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
#degree.
import numpy as np
print("sine:angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cosine:angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tangent:angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

sine:angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine:angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent:angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [17]:
#Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
#index labels
import pandas as pd
import numpy as np

exam_data  = {'name': ['sameer', 'sandeep', 'deepti', 'pooja', 'varun', 'vandana', 'sunil', 'shruti', 'ashwani', 'tejas'],
        'score': [60, 90, 75.5, 20, 15, 20, 30.5, 33, 80, 55],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'yes', 'yes', 'no', 'no', 'no', 'no', 'yes', 'yes', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print(df)

      name  score  attempts qualify
a   sameer   60.0         1     yes
b  sandeep   90.0         3     yes
c   deepti   75.5         2     yes
d    pooja   20.0         3      no
e    varun   15.0         2      no
f  vandana   20.0         3      no
g    sunil   30.5         1      no
h   shruti   33.0         1     yes
i  ashwani   80.0         2     yes
j    tejas   55.0         1     yes


In [18]:
#Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.
import pandas as pd
import numpy as np

exam_data  = {'name': ['sameer', 'sandeep', 'deepti', 'pooja', 'varun', 'vandana', 'sunil', 'shruti', 'ashwani', 'tejas'],
        'score': [60, 90, 75.5, 20, 15, 20, 30.5, 33, 80, 55],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'yes', 'yes', 'no', 'no', 'no', 'no', 'yes', 'yes', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data , index=labels)
print(df[['name', 'score']])


      name  score
a   sameer   60.0
b  sandeep   90.0
c   deepti   75.5
d    pooja   20.0
e    varun   15.0
f  vandana   20.0
g    sunil   30.5
h   shruti   33.0
i  ashwani   80.0
j    tejas   55.0


In [21]:
#Write a Pandas program to join the two given dataframes along rows and assign all data.
import pandas as pd

student_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['shashi', 'vijay', 'gulshan', 'mohit', 'ekta'], 
        'marks': [200, 210, 190, 222, 199]})

student_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['pooja', 'santwana', 'mohini', 'divya', 'preeti'], 
        'marks': [201, 200, 198, 219, 201]})

print(student_data1)
print("..............................................")
print(student_data2)

print("..............................................")
print("concatination of two dataframes:")
result_data = pd.concat([student_data1, student_data2])
print(result_data)

  student_id     name  marks
0         S1   shashi    200
1         S2    vijay    210
2         S3  gulshan    190
3         S4    mohit    222
4         S5     ekta    199
..............................................
  student_id      name  marks
0         S4     pooja    201
1         S5  santwana    200
2         S6    mohini    198
3         S7     divya    219
4         S8    preeti    201
..............................................
concatination of two dataframes:
  student_id      name  marks
0         S1    shashi    200
1         S2     vijay    210
2         S3   gulshan    190
3         S4     mohit    222
4         S5      ekta    199
0         S4     pooja    201
1         S5  santwana    200
2         S6    mohini    198
3         S7     divya    219
4         S8    preeti    201


In [22]:
#Write a Pandas program to detect missing values of a given DataFrame. Display True or False.
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)
df = pd.DataFrame({
'ord_no':[70001,np.nan,70002,70004,np.nan,70005,np.nan,70010,70003,70012,np.nan,70013],
'purch_amt':[150.5,270.65,65.26,110.5,948.5,2400.6,5760,1983.43,2480.4,250.45, 75.29,3045.6],
'ord_date': ['2012-10-05','2012-09-10',np.nan,'2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'customer_id':[3002,3001,3001,3003,3002,3001,3001,3004,3003,3002,3001,3001],
'salesman_id':[5002,5003,5001,np.nan,5002,5001,5001,np.nan,5003,5002,5003,np.nan]})
print("Original Orders DataFrame:")
print(df)
print("\nMissing values of the said dataframe:")
print(df.isna())

Original Orders DataFrame:
     ord_no  purch_amt    ord_date  customer_id  salesman_id
0   70001.0     150.50  2012-10-05         3002       5002.0
1       NaN     270.65  2012-09-10         3001       5003.0
2   70002.0      65.26         NaN         3001       5001.0
3   70004.0     110.50  2012-08-17         3003          NaN
4       NaN     948.50  2012-09-10         3002       5002.0
5   70005.0    2400.60  2012-07-27         3001       5001.0
6       NaN    5760.00  2012-09-10         3001       5001.0
7   70010.0    1983.43  2012-10-10         3004          NaN
8   70003.0    2480.40  2012-10-10         3003       5003.0
9   70012.0     250.45  2012-06-27         3002       5002.0
10      NaN      75.29  2012-08-17         3001       5003.0
11  70013.0    3045.60  2012-04-25         3001          NaN

Missing values of the said dataframe:
    ord_no  purch_amt  ord_date  customer_id  salesman_id
0    False      False     False        False        False
1     True      False    

In [23]:
#Write a Pandas program to create and display a one-dimensional array-like object containing an array of
#data.
import pandas as pd
ds = pd.Series([1, 3, 5, 7, 9])
print(ds)

0    1
1    3
2    5
3    7
4    9
dtype: int64
